api/urls.py
from django.urls import path
from api.views import *

app_name = "api"

urlpatterns = [
    path(r'definition/', definition, name='definition'),
    # path(r'', main_page, name="main_page"),
    # path(r'edit_profile/', update_profile, name='update_profile'),
    # path(r'change_password/', change_password, name="change_password"),
    # path(r'create_definition/', create_definition, name='create_definition'),
    # path(r'term/<int:pk>',  TermView.as_view(), name='term'),
    # path(r'activate_user/', activate_user, name='activate_user'),
    # path(r'random_definition', random_definition, name='random_definition'),
    # path(r'personal_definitions/', personal_definitions, name='personal_definitions'),
    # path(r'definition/<int:pk>', definition, name='definition'),
    # path(r'definition/edit/<int:pk>', edit_definition, name='edit_definition'),
    # path(r'definition/check/<int:pk>', request_for_definition, name='request_for_definition'),
    # path(r'page_not_found/', page_not_found, name='page_not_found'),
    # path(r'definition/like', like, name='like'),
    # path(r'definition/dislike', dislike, name='dislike'),
    # path(r'favourite/', favourite, name='favourite'),
    # path(r'favourites/', favourites, name='favourites_list'),
    # path(r'search/', search, name='search'),
    # path(r'requests/', requests_pub, name='requests_pub'),
    # path(r'profile/<int:pk>', UserDetailView.as_view(), name='profile')
]

urban_dictionary/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

from urban_dictionary import settings

urlpatterns = [
    path(r'admin/', admin.site.urls),
    path(r'urban/', include('website.urls', namespace="website")),
    path(r'api/', include('api.urls', namespace="api")),
    path(r'accounts/', include('django_registration.backends.activation.urls')),
    path(r'accounts/', include('django.contrib.auth.urls')),
    path(r'', RedirectView.as_view(url='/urban/', permanent=True)),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'website.views.custom_handler404'
handler500 = 'website.views.custom_handler500'

website/urls.py
from django.urls import path
from website.views import *

app_name = "website"

urlpatterns = [
    path(r'', main_page, name="main_page"),
    path(r'edit_profile/', update_profile, name='update_profile'),
    path(r'change_password/', change_password, name="change_password"),
    path(r'create_definition/', create_definition, name='create_definition'),
    path(r'term/<int:pk>', TermView.as_view(), name='term'),
    path(r'activate_user/', activate_user, name='activate_user'),
    path(r'random_definition', random_definition, name='random_definition'),
    path(r'personal_definitions/', personal_definitions, name='personal_definitions'),
    path(r'user_definitions/<int:pk>', user_definitions, name='user_definitions'),
    path(r'definition/<int:pk>', definition, name='definition'),
    path(r'definition/edit/<int:pk>', edit_definition, name='edit_definition'),
    path(r'definition/check/<int:pk>', request_for_definition, name='request_for_definition'),
    path(r'requests_update_status/', requests_for_update_status, name='requests_for_update_status'),
    path(r'definition/like', like, name='like'),
    path(r'definition/dislike', dislike, name='dislike'),
    path(r'favourite/', favourite, name='favourite'),
    path(r'favourites/', favourites, name='favourites_list'),
    path(r'search/', search, name='search'),
    path(r'requests/', requests_pub, name='requests_pub'),
    path(r'profile/<int:pk>', UserDetailView.as_view(), name='profile'),
    path(r'notifications', notifications, name='notifications'),
    path(r'update_status/<int:pk>/<str:answer>', update_status, name='update_status'),
    path(r'create_request_for_update_status', create_request_for_update_status,
         name='create_request_for_update_status'),
    path(r'support/', ask_support, name='support'),
    path(r'support/<int:pk>', answer_support, name='answer_support'),
    path(r'block/<int:pk>', block, name='block'),
    path(r'unblock/<int:pk>', unblock, name='unblock'),
    path(r'drop_file', drop_file, name='drop_file')
]

website/models.py
from datetime import datetime, timedelta, date

from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.template.defaultfilters import truncatechars, truncatewords
from django.utils import timezone

from website.enums import *


class CustomUser(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="custom_user")
    description = models.TextField(verbose_name="О себе")
    email = models.CharField(max_length=50, verbose_name="Почта")
    role = models.IntegerField(choices=ROLE_CHOICES, blank=False, null=False, default=ROLE_CHOICES[0][0],
                               verbose_name="Роль")
    date_registration = models.DateTimeField(auto_now_add=True, blank=False, verbose_name="Дата регистрации")
    status = models.IntegerField(choices=STATUSES, blank=False, null=False, default=STATUSES[2][0],
                                 verbose_name="Статус")

    photo = models.ImageField(upload_to='profile_pics', default='profile_pics/default.jpg')

    def get_rating(self):
        return sum(map(lambda x: x.get_likes() - x.get_dislikes(), self.definitions.all()))

    def __str__(self):
        return self.user.username

    def is_moderator(self):
        return self.role == ROLE_CHOICES[1][0]

    def is_admin(self):
        return self.role == ROLE_CHOICES[2][0]

    def get_new_notification(self):
        return len(self.notifications.filter(new=True))

    def get_ratio_lik_to_dis(self):
        likes = sum(map(lambda x: x.get_likes(), self.definitions.all()))
        dislikes = sum(map(lambda x: x.get_dislikes(), self.definitions.all()))
        return likes * 100 / (likes + dislikes)

    def is_ready_to_update(self):
        return len(self.definitions.all().exclude(
            date__isnull=True)) > DEF_AMOUNT and self.get_rating() >= ALL_ESTIMATES and self.get_ratio_lik_to_dis() >= PERCENTAGE_OF_LIKES

    def is_block(self):
        block = self.blocking.all().filter(active=True)
        if len(block) == 0:
            return False
        block = block[0]
        if block.expiration_date <= timezone.now():
            block.active = False
            block.save()
            block.user.is_active = True
            block.user.save()
            return False
        return True


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        CustomUser.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.custom_user.save()


class Term(models.Model):
    name = models.CharField(max_length=200, verbose_name="Термин", unique=True)

    def __str__(self):
        return self.name


class Definition(models.Model):
    term = models.ForeignKey(Term, related_name='definitions', on_delete=models.CASCADE,
                             blank=False, null=False, verbose_name='Термин')
    description = models.TextField(verbose_name="Описание термина")
    date = models.DateTimeField(blank=True, verbose_name="Дата публикации", null=True)
    author = models.ForeignKey(CustomUser, related_name='definitions', on_delete=models.CASCADE,
                               blank=False, null=False, verbose_name='Автор')
    source = models.TextField(verbose_name="Ссылка на источник/первоисточник", default=None, blank=True, null=True)

    def __str__(self):
        return "Определение %s - автор %s" % (self.term, self.author)

    def get_likes(self):
        return self.estimates.filter(estimate=1).count()

    def get_dislikes(self):
        return self.estimates.filter(estimate=0).count()

    def get_primary_example(self):
        return self.examples.get(primary=True).example

    def is_publish(self):
        if self.date is None:
            return False
        return True

    def get_cur_status(self):
        reqs = self.requests.all()
        if len(reqs) == 0:
            return -1
        return reqs.first().status

    @property
    def short_description(self):
        return truncatewords(self.description, 80)

    @classmethod
    def get_top_for_week(cls):
        result = []
        for i in range(7):
            day = date.today() - timedelta(i)
            defs = Definition.objects.filter(date__day=day.day, date__month=day.month, date__year=day.year)
            x = {}
            for d in defs:
                # TODO - temporary change
                if d.get_dislikes() + d.get_likes() >= 5:
                    try:
                        x[d] = d.get_likes() / d.get_dislikes()
                    except ZeroDivisionError:
                        x[d] = d.get_likes()
            m = 0
            top_def = None
            for d, proportion in x.items():
                if proportion > m:
                    top_def = d
            if top_def:
                result.append(top_def)
        return result


class Example(models.Model):
    definition = models.ForeignKey(Definition, related_name='examples', on_delete=models.CASCADE,
                                   blank=False, null=False, verbose_name='Ссылка на определение')
    example = models.TextField(verbose_name="Пример использования")
    primary = models.BooleanField(default=False, blank=False, null=False, verbose_name="Основной пример")

    def __str__(self):
        return "Пример %s - %s" % (self.example, self.primary)


class UploadData(models.Model):
    definition = models.ForeignKey(Definition, related_name='files', on_delete=models.CASCADE,
                                   blank=False, null=False, verbose_name='Ссылка на определение')
    header_for_file = models.CharField(max_length=100, null=True, blank=True)
    image = models.ImageField()

    def __str__(self):
        return '%s - %s - %s' % (
            self.definition, self.header_for_file, self.image.url)


class RequestForPublication(models.Model):
    definition = models.ForeignKey(Definition, related_name='requests', on_delete=models.CASCADE,
                                   blank=False, null=False, verbose_name='Ссылка на определение')
    status = models.IntegerField(choices=STATUSES_FOR_REQUESTS, blank=False, null=False,
                                 default=STATUSES_FOR_REQUESTS[0][0],
                                 verbose_name="Статус публикации")
    reason = models.TextField(verbose_name="Причина отклонения", blank=False, null=False)

    old_request = models.ForeignKey("self", blank=True, null=True, verbose_name="Старый запрос на публикацию",
                                    on_delete=models.SET_NULL)

    date_creation = models.DateTimeField(blank=False, null=False, verbose_name="Дата создания запроса")

    def __str__(self):
        return "Запрос на публикацию определения %s" % self.definition

    def is_new(self):
        return self.status == STATUSES_FOR_REQUESTS[0][0]


class Comment(models.Model):
    definition = models.ForeignKey(Definition, related_name='comments', on_delete=models.CASCADE,
                                   blank=False, null=False, verbose_name='Ссылка на определение')
    other_comment = models.ForeignKey("self", blank=True, null=True, verbose_name="Корневой комментарий",
                                      on_delete=models.CASCADE)

    text = models.TextField(verbose_name="Комментарий", blank=False)

    date_creation = models.DateTimeField(auto_now_add=True, blank=False, verbose_name="Дата")

    author = models.ForeignKey(CustomUser, related_name='comments', on_delete=models.CASCADE,
                               blank=False, null=False, verbose_name='Автор комментария')

    def __str__(self):
        return "Комментарий %s от %s " % (self.text, self.author)


class Rating(models.Model):
    definition = models.ForeignKey(Definition, related_name='estimates', on_delete=models.CASCADE,
                                   blank=False, null=False, verbose_name='Ссылка на определение')
    user = models.ForeignKey(CustomUser, related_name='estimates', on_delete=models.CASCADE,
                             blank=False, null=False, verbose_name='Пользователь')
    estimate = models.IntegerField(choices=RATING_VALUES, blank=False, null=False,
                                   default=RATING_VALUES[0][0],
                                   verbose_name="Оценка")

    def __str__(self):
        return "%s определения %s от %s " % (self.estimate, self.definition, self.user)


class Blocking(models.Model):
    user = models.ForeignKey(CustomUser, related_name='blocking', on_delete=models.CASCADE,
                             blank=False, null=False, verbose_name='Пользователь')
    reason = models.TextField(verbose_name="Причина блокировки", blank=False)
    date_creation = models.DateTimeField(auto_now_add=True, blank=False, verbose_name="Дата создания блокировки")
    expiration_date = models.DateTimeField(blank=True, null=True, verbose_name="Дата истекания блокировки")
    active = models.BooleanField(blank=False, null=False, default=True, verbose_name="Активная ")

    def __str__(self):
        return "Блокировка пользователя %s" % self.user


class Favorites(models.Model):
    definition = models.ForeignKey(Definition, related_name='favorites', on_delete=models.CASCADE,
                                   blank=False, null=False, verbose_name='Ссылка на определение')
    user = models.ForeignKey(CustomUser, related_name='favorites', on_delete=models.CASCADE,
                             blank=False, null=False, verbose_name='Ссылка на пользователя')

    def __str__(self):
        return "Избранное пользователя %s - %s " % (self.user, self.definition)


class Notification(models.Model):
    date_creation = models.DateTimeField(blank=False, null=False, verbose_name="Дата уведомления")
    action_type = models.IntegerField(choices=ACTION_TYPES, blank=False, null=False,
                                      default=ACTION_TYPES[0][0],

website/forms.py
from django import forms
from django.contrib.auth.models import User
from website.models import CustomUser, Support


class EditUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name')


class EditProfileForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ('description', 'photo')

website/templates/website/support.html
{% extends 'website/base/base_page.html' %}
{% block title %}
    Поддержка
{% endblock %}
{% block content %}
    <div class="card">
        <div class="card-body">
            <div class="e-profile">
                <br>
                <h3>Задайте вопрос</h3>
                <hr>
                <form method="post" action="{% url "website:support" %}">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col">
                            <div class="form-group">
                                <label for="id_name">Ваше имя</label>
                                <input class="form-control" type="text"
                                       name="name"
                                       id="id_name"
                                       {% if user.is_authenticated %}value="{{ user.first_name }}"{% endif %} required>
                            </div>
                            <div class="form-group">
                                <label for="id_email">Ваша почта</label>
                                <input class="form-control" type="text"
                                       name="email"
                                       id="id_email"
                                       {% if user.is_authenticated %}value="{{ user.email }}"{% endif %} required>
                            </div>
                            <div class="form-group">
                                <label for="id_question">Вопрос</label>
                                <textarea class="form-control" cols="5"
                                          name="question"
                                          id="id_question" required></textarea>
                            </div>
                        </div>
                    </div>
                    <button class="btn btn-primary" type="submit">Отправить</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

website/templates/website/support_answer.html
{% extends 'website/base/base_page.html' %}
{% block title %}
    Ответ на вопрос
{% endblock %}
{% block content %}
    <div class="card">
        <div class="card-body">
            <div class="e-profile">
                <div class="text-sm-left mb-2 mb-sm-0">
                    <h4 class="pt-sm-2 pb-1 mb-0 text-nowrap">Вопрос от пользователя: {{ question.name }}</h4>
                    <br>
                    <div class="jumbotron"><p class="mb-0">{{ question.question }}</p></div>
                    <p class="mb-0" style="color: gray; font-size: 18px">Ответ будет отправлен на
                        почту {{ question.email }}</p>
                </div>
                <form method="post" action="{% url "website:answer_support" question.id %}">
                    {% csrf_token %}
                    <br>
                    <hr style="margin-top: 20px">
                    <h4>Ответ на вопрос</h4>
                    <div class="row" style="margin-top: 20px">
                        <div class="col">
                            <div class="form-group">
                                <textarea class="form-control" cols="5"
                                          name="answer"
                                          id="id_answer" required></textarea>
                            </div>
                        </div>
                    </div>
                    <button class="btn btn-primary" type="submit">Отправить</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

website/templates/website/support_done.html
{% extends 'website/base/base_page.html' %}
{% block title %}Сообщение отправлено{% endblock %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm-9 mx-auto">
                <h2>Ваш вопрос был отправлен администрации.</h2><br>
                <h3>Ответ вы получите на почту {{ email }}. Среднее время ожидания: 2-3 рабочих дня.</h3>
            </div>
        </div>
    </div>
{% endblock %}

website/templates/website/term_page.html
{% extends 'website/base/base_page.html' %}
{% load static %}
{% load custom_tags %}
{% block title %}
    {{ term.name }}
{% endblock %}

{% block extrahead %}
    <link rel="stylesheet" href="{% static 'stats/dataTables.bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'stats/tableexport.min.css' %}">

    <script src="{% static 'stats/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'stats/dataTables.bootstrap.min.js' %}"></script>

    {# tableexport.js staff #}
    <script lang="javascript" src="{% static 'stats/xlsx.core.min.js' %}"></script>
    <script src="{% static 'stats/FileSaver.min.js' %}"></script>
    <script src="{% static 'stats/tableexport.min.js' %}"></script>
{% endblock %}

{% block content %}

    {% for definition in term.definitions.all %}
        <div style="margin: 30px">
            <br>
            <div class="row">
                <div class="col-md-5">
                    <a href={% url 'website:term' definition.term.id %}><h3>{{ definition.term.name }}</h3></a>
                    {% if user.custom_user == definition.author %}
                        <p>Статус статьи - {% if definition.is_publish %}
                            <i style="color: green">Опубликовано</i>
                        {% else %}
                            {% if  definition.get_cur_status == 1 %}
                                <i style="color: #0a1cff">На рассмотрении </i>
                            {% elif definition.get_cur_status == 2 %}
                                <i style="color: #ff8820">Отклонен </i>
                                <br><br>
                                <a href="{% url "website:edit_definition" definition.id %}"
                                   class="btn btn-light" style="background: #f9870b; color: white">Исправить</a>
                            {% elif definition.get_cur_status == 4 %}
                                <i style="color: #ff1118">Отклонен навсегда </i>
                            {% endif %}
                        {% endif %}</p>
                    {% endif %}
                </div>
                <div class="col-md-6">
                    <h5>Автор статьи - {% if definition.author.is_block %}
                        {{ definition.author }}
                    {% else %}
                        <a href={% url 'website:profile' definition.author.id %}>{{ definition.author }}</a>
                    {% endif %}

                    </h5>
                    {% if definition.author.user.last_name != "" or definition.author.user.last_name != "" %}
                        <h6 style="color: #4b4b4b">{{ definition.author.user.last_name }} {{ definition.author.user.first_name }}</h6>
                    {% endif %}
                    {% if definition.is_publish %}
                        {% if definition.date %}<p><i>Дата публикации - {{ definition.date }}</i></p>{% endif %}
                    {% endif %}
                </div>
                {% if definition.is_publish %}
                    <div class="col-md-1">
                        <p class="{% is_favoured definition user %}" id="favorite{{ definition.pk }}"
                           name="{{ definition.pk }}" data-toggle="tooltip" data-placement="bottom"
                           title="Добавить в избранное"><i class=" fa fa-heart"></i></p>
                    </div>
                    <script>
                        $('#favorite{{ definition.pk }}').click(function () {
                            $.ajax({
                                type: "POST",
                                url: "{% url 'website:favourite' %}",
                                data: {'def_id': $(this).attr('name'), 'csrfmiddlewaretoken': '{{ csrf_token }}'},
                                dataType: "json",
                                success: function (response) {
                                    if (response.colour === 'black') {
                                        $('#favorite{{ definition.pk }}').removeClass("favoritesadded").addClass("favorites");
                                    } else {
                                        $('#favorite{{ definition.pk }}').removeClass("favorites").addClass("favoritesadded");
                                    }
                                },
                                fail: function (response) {
                                    alert(response.responseText)
                                },
                                error: function (rs, e) {
                                    debugger
                                    alert(rs.responseText);
                                }
                            });
                        })
                    </script>
                {% endif %}
            </div>
            <h3>Описание</h3>
            <a href="{% url "website:definition" definition.id %}" style="text-decoration: none">
                <div class="div-info">
                    <p>{{ definition.short_description }}</p>
                </div>
            </a>
            <h3>Примеры</h3>
            <div class="jumbotron">
                <p>{{ definition.get_primary_example }}</p>
            </div>
            <hr>
            {% if definition.is_publish %}
                <button {% if not user.is_authenticated %} disabled {% endif %} id="like{{ definition.pk }}"
                                                           name="{{ definition.pk }}"
                                                           class="btn {% is_liked definition user %}"><i
                        class="fa fa-thumbs-up">&nbsp{{ definition.get_likes }}</i></button>
                <button {% if not user.is_authenticated %} disabled {% endif %} id="dislike{{ definition.pk }}"
                                                           name="{{ definition.pk }}"
                                                           class="btn {% is_disliked definition user %}"><i
                        class="fa fa-thumbs-down">&nbsp{{ definition.get_dislikes }}</i></button>
                <br>
                <br>
                <script>
                    $('#like{{ definition.pk }}').click(function () {
                        $.ajax({
                            type: "POST",
                            url: "{% url 'website:like' %}",
                            data: {'def_id': $(this).attr('name'), 'csrfmiddlewaretoken': '{{ csrf_token }}'},
                            dataType: "json",
                            success: function (response) {
                                $('#like{{ definition.pk }}').html("<i class=\"fa fa-thumbs-up\">&nbsp" + response.likes_count + "</i>");
                                $('#dislike{{ definition.pk }}').html("<i class=\"fa fa-thumbs-down\">&nbsp" + response.dislikes_count + "</i>");
                                $("#like{{ definition.pk }}").removeClass();
                                $("#dislike{{ definition.pk }}").removeClass();
                                if (response.is_liked) {
                                    $("#like{{ definition.pk }}").addClass("btn btn-success");
                                    $("#dislike{{ definition.pk }}").addClass("btn btn-outline-danger");
                                } else {
                                    $("#like{{ definition.pk }}").addClass("btn btn-outline-success");
                                    $("#dislike{{ definition.pk }}").addClass("btn btn-outline-danger");
                                }
                            },
                            error: function (rs, e) {
                                alert(rs.responseText);
                            }
                        });
                    })
                </script>
                <script>
                    $('#dislike{{ definition.pk }}').click(function () {
                        $.ajax({
                            type: "POST",
                            url: "{% url 'website:dislike' %}",
                            data: {'def_id': $(this).attr('name'), 'csrfmiddlewaretoken': '{{ csrf_token }}'},
                            dataType: "json",
                            success: function (response) {
                                $('#like{{ definition.pk }}').html("<i class=\"fa fa-thumbs-up\">&nbsp" + response.likes_count + "</i>");
                                $('#dislike{{ definition.pk }}').html("<i class=\"fa fa-thumbs-down\">&nbsp" + response.dislikes_count + "</i>");
                                $("#like{{ definition.pk }}").removeClass();
                                $("#dislike{{ definition.pk }}").removeClass();
                                if (response.is_disliked) {
                                    $("#like{{ definition.pk }}").addClass("btn btn-outline-success");
                                    $("#dislike{{ definition.pk }}").addClass("btn btn-danger");
                                } else {
                                    $("#like{{ definition.pk }}").addClass("btn btn-outline-success");
                                    $("#dislike{{ definition.pk }}").addClass("btn btn-outline-danger");
                                }
                            },
                            error: function (rs, e) {
                                alert(rs.responseText);
                            }
                        });
                    })
                </script>
            {% endif %}
        </div>
    {% endfor %}


{% endblock %}

{% block scripts %}
    <script>

        $(document).ready(function () {
            $('res-table').DataTable({
                scrollX: true,
                "bPaginate": false,
                scrollCollapse: true,
                "language": {
                    "url": "{% static 'stats/Russian.json' %}"
                },
                "info": false
            });

            TableExport.prototype.formatConfig.xlsx.buttonContent = "Экспорт в xlsx";
            TableExport.prototype.formatConfig.csv.buttonContent = "Экспорт в csv";
            TableExport(document.getElementById("result-table-m"), {
                headers: true,                              // (Boolean), display table headers (th or td elements) in the <thead>, (default: true)
                formats: ['xlsx', 'csv'],                   // (String[]), filetype(s) for the export, (default: ['xlsx', 'csv', 'txt'])
                filename: '{{ tournament.name }}' + ' Cтат.',                             // (id, String), filename for the downloaded file, (default: 'id')
                bootstrap: true,                           // (Boolean), style buttons using bootstrap, (default: true)
                exportButtons: true,                        // (Boolean), automatically generate the built-in export buttons for each of the specified formats (default: true)
                position: 'bottom',                         // (top, bottom), position of the caption element relative to table, (default: 'bottom')
                ignoreRows: null,                           // (Number, Number[]), row indices to exclude from the exported file(s) (default: null)
                ignoreCols: null,                           // (Number, Number[]), column indices to exclude from the exported file(s) (default: null)
                trimWhitespace: false
            });

            TableExport(document.getElementById("result-table-w"), {
                headers: true,                              // (Boolean), display table headers (th or td elements) in the <thead>, (default: true)
                formats: ['xlsx', 'csv'],                   // (String[]), filetype(s) for the export, (default: ['xlsx', 'csv', 'txt'])
                filename: '{{ tournament.name }}' + ' Cтат.',                             // (id, String), filename for the downloaded file, (default: 'id')
                bootstrap: true,                           // (Boolean), style buttons using bootstrap, (default: true)
                exportButtons: true,                        // (Boolean), automatically generate the built-in export buttons for each of the specified formats (default: true)
                position: 'bottom',                         // (top, bottom), position of the caption element relative to table, (default: 'bottom')
                ignoreRows: null,                           // (Number, Number[]), row indices to exclude from the exported file(s) (default: null)
                ignoreCols: null,                           // (Number, Number[]), column indices to exclude from the exported file(s) (default: null)
                trimWhitespace: false
            });


        });
    </script>
{% endblock %}