api/urls.py
from django.urls import path
from api.views import *

app_name = "api"

urlpatterns = [
    path(r'definition/', definition, name='definition'),
    # path(r'', main_page, name="main_page"),
    # path(r'edit_profile/', update_profile, name='update_profile'),
    # path(r'change_password/', change_password, name="change_password"),
    # path(r'create_definition/', create_definition, name='create_definition'),
    # path(r'term/<int:pk>',  TermView.as_view(), name='term'),
    # path(r'activate_user/', activate_user, name='activate_user'),
    # path(r'random_definition', random_definition, name='random_definition'),
    # path(r'personal_definitions/', personal_definitions, name='personal_definitions'),
    # path(r'definition/<int:pk>', definition, name='definition'),
    # path(r'definition/edit/<int:pk>', edit_definition, name='edit_definition'),
    # path(r'definition/check/<int:pk>', request_for_definition, name='request_for_definition'),
    # path(r'page_not_found/', page_not_found, name='page_not_found'),
    # path(r'definition/like', like, name='like'),
    # path(r'definition/dislike', dislike, name='dislike'),
    # path(r'favourite/', favourite, name='favourite'),
    # path(r'favourites/', favourites, name='favourites_list'),
    # path(r'search/', search, name='search'),
    # path(r'requests/', requests_pub, name='requests_pub'),
    # path(r'profile/<int:pk>', UserDetailView.as_view(), name='profile')
]

urban_dictionary/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

from urban_dictionary import settings

urlpatterns = [
    path(r'admin/', admin.site.urls),
    path(r'urban/', include('website.urls', namespace="website")),
    path(r'api/', include('api.urls', namespace="api")),
    path(r'accounts/', include('django_registration.backends.activation.urls')),
    path(r'accounts/', include('django.contrib.auth.urls')),
    path(r'', RedirectView.as_view(url='/urban/', permanent=True)),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'website.views.custom_handler404'
handler500 = 'website.views.custom_handler500'

website/urls.py
from django.urls import path
from website.views import *

app_name = "website"

urlpatterns = [
    path(r'', main_page, name="main_page"),
    path(r'edit_profile/', update_profile, name='update_profile'),
    path(r'change_password/', change_password, name="change_password"),
    path(r'create_definition/', create_definition, name='create_definition'),
    path(r'term/<int:pk>', TermView.as_view(), name='term'),
    path(r'activate_user/', activate_user, name='activate_user'),
    path(r'random_definition', random_definition, name='random_definition'),
    path(r'personal_definitions/', personal_definitions, name='personal_definitions'),
    path(r'user_definitions/<int:pk>', user_definitions, name='user_definitions'),
    path(r'definition/<int:pk>', definition, name='definition'),
    path(r'definition/edit/<int:pk>', edit_definition, name='edit_definition'),
    path(r'definition/check/<int:pk>', request_for_definition, name='request_for_definition'),
    path(r'requests_update_status/', requests_for_update_status, name='requests_for_update_status'),
    path(r'definition/like', like, name='like'),
    path(r'definition/dislike', dislike, name='dislike'),
    path(r'favourite/', favourite, name='favourite'),
    path(r'favourites/', favourites, name='favourites_list'),
    path(r'search/', search, name='search'),
    path(r'requests/', requests_pub, name='requests_pub'),
    path(r'profile/<int:pk>', UserDetailView.as_view(), name='profile'),
    path(r'notifications', notifications, name='notifications'),
    path(r'update_status/<int:pk>/<str:answer>', update_status, name='update_status'),
    path(r'create_request_for_update_status', create_request_for_update_status,
         name='create_request_for_update_status'),
    path(r'support/', ask_support, name='support'),
    path(r'support/<int:pk>', answer_support, name='answer_support'),
    path(r'block/<int:pk>', block, name='block'),
    path(r'unblock/<int:pk>', unblock, name='unblock'),
    path(r'drop_file', drop_file, name='drop_file')
]

website/forms.py
from django import forms
from django.contrib.auth.models import User
from website.models import CustomUser, Support


class EditUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name')


class EditProfileForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ('description', 'photo')

website/views.py
from datetime import datetime, timedelta
import random
import time
import os.path

from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import PasswordChangeForm
from django.core.files.storage import FileSystemStorage
from django.db import transaction
from django.db.models import Q
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.shortcuts import render, redirect, get_object_or_404, render_to_response
from django.views.decorators.http import require_POST
from django_registration.forms import User
from django.core.mail import send_mail
from django.views import View
from django.template import RequestContext

from website.enums import STATUSES_FOR_REQUESTS, ACTION_TYPES, USER, DEF, RFP, RUPS, SUP, AMOUNT_NOTIF_DISPLAY
from urban_dictionary.settings import EMAIL_HOST_USER
from website.tasks import unblock_user

try:
    from django.utils import simplejson as json
except ImportError:
    import json

from website.forms import *
from website.models import Definition, CustomUser, Example, UploadData, Rating, RequestForPublication, Favorites, \
    Notification, RequestUpdateStatus, Blocking, Term, STATUSES, ROLE_CHOICES


def main_page(request):
    return render(request, 'website/main_page.html',
                  {'definitions': Definition.get_top_for_week, 'popular_for_week': True})


def custom_handler404(request, exception, template_name="page_not_found.html"):
    return render(request, 'website/base/page_not_found.html', {}, status=404)


def custom_handler500(request):
    return render(request, 'website/base/server_error.html', {}, status=500)


@login_required
@transaction.atomic
def activate_user(request):
    request.user.custom_user.status = STATUSES[0][0]
    request.user.save()
    return redirect('website:update_profile')


def ask_support(request):
    if not request.user.is_anonymous:
        if request.user.custom_user.is_admin():
            if request.method == 'POST':
                return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))
            return render(request, 'website/support_list.html',
                          {'questions': Support.objects.filter(answer__isnull=True).order_by("-date_creation")})
    if request.method == 'POST':
        question = Support(question=request.POST["question"], name=request.POST["name"], email=request.POST["email"],
                           date_creation=datetime.now())
        if not request.user.is_anonymous:
            question.user = request.user.custom_user
        question.save()
        for admin in CustomUser.objects.filter(role=3):
            Notification(date_creation=datetime.now(), user=admin,
                         action_type=ACTION_TYPES[14][0],
                         models_id="%s%s" % (SUP, question.id)).save()
        return render(request, 'website/support_done.html', {'email': question.email})
    return render(request, 'website/support.html', {})


@login_required
def answer_support(request, pk):
    if request.user.custom_user.is_admin():
        question = get_object_or_404(Support, pk=pk)
        if request.method == 'POST':
            question.answer = request.POST['answer']
            question.save()

            BASE = os.path.dirname(os.path.abspath(__file__))
            with open(os.path.join(BASE, "support_mail.txt"), 'r', encoding="utf-8") as support_mail:
                email_text = support_mail.read() \
                    .replace("question_Q8Vx q]vYfs$*7c,<tyfP|SCdr+wl+m2N{.uY.[a9&mR1zmHL}8[Xz V&36X||0t",
                             question.question) \
                    .replace("answer_q+W{ceC)}*<la~K9C{)>CLfUNY6[?c|u=JVT[)`L8*R|=qw,C?x &A:Bvv^tQD^D", question.answer)
                send_mail('Ответ на вопрос на сайте {}'.format(request.META['HTTP_HOST']),
                          email_text,
                          EMAIL_HOST_USER,
                          [question.email],
                          fail_silently=False)
            if not question.user is None:
                Notification(date_creation=datetime.now(), user=question.user,
                             action_type=ACTION_TYPES[11][0],
                             models_id="%s%s" % (SUP, question.id)).save()
            return redirect('website:support')
        return render(request, 'website/support_answer.html', {
            'question': question
        })
    else:
        redirect('website:main_page')


@login_required
@require_POST
def change_password(request):
    password_form = PasswordChangeForm(user=request.user, data=request.POST)
    if password_form.is_valid():
        password_form.save()
        update_session_auth_hash(request, password_form.user)
        return redirect('website:profile', pk=request.user.id)
    else:
        request.session['change_password_msg'] = password_form.errors
        return redirect('website:update_profile')


@login_required
@transaction.atomic
def update_profile(request):
    password_form = PasswordChangeForm(user=request.user)
    if request.method == 'POST':
        user_form = EditUserForm(request.POST, instance=request.user)
        profile_form = EditProfileForm(request.POST, instance=request.user.custom_user)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            user = profile_form.save(commit=False)
            user.photo = request.FILES.get('photo', user.photo)
            user.save()
            return redirect('website:profile', pk=user.id)
    else:
        user_form = EditUserForm(instance=request.user)
        profile_form = EditProfileForm(instance=request.user.custom_user)
        password_form._errors = request.session.pop('change_password_msg', None)
    return render(request, 'website/edit_profile.html', {
        'user_form': user_form,
        'profile_form': profile_form,
        'password_form': password_form,
        'role': ROLE_CHOICES[request.user.custom_user.role - 1][1]
    })


class UserDetailView(View):

    def get(self, request, pk):
        profile = get_object_or_404(User, pk=pk)
        if profile.custom_user.is_block():
            if request.user.is_anonymous:
                raise Http404()
            if not request.user.custom_user.is_admin():
                raise Http404()
        user_definitions = Definition.objects.filter(author_id__exact=pk)
        user_rating = str(sum(map(lambda x: x.get_likes() - x.get_dislikes(), user_definitions)))
        definition_number = Definition.objects.filter(author_id__exact=pk).count()
        return render(request, 'website/profile.html',
                      {'profile': profile,
                       'role': ROLE_CHOICES[profile.custom_user.role - 1][1],
                       'rating': user_rating,
                       'definition_number': definition_number})


@login_required
def create_definition(request):
    current_user = CustomUser.objects.get(user=request.user)
    if request.method == 'POST':
        term = Term.objects.filter(name=request.POST["name"]).first()
        if term is None:
            term = Term(name=request.POST["name"])
            term.save()
        definition = Definition(term=term, description=request.POST["description"],
                                source=request.POST["source"],
                                author=current_user)
        definition.save()
        if current_user.is_moderator() or current_user.is_admin():
            definition.date = datetime.now()
            definition.save()
        else:
            cur_date = datetime.now()
            rfp = RequestForPublication(definition=definition, date_creation=cur_date)
            rfp.save()
            for admin in CustomUser.objects.filter(role=3):
                Notification(date_creation=cur_date, user=admin, action_type=ACTION_TYPES[12][0],
                             models_id="%s%s %s%s" % (USER, current_user.id, RFP, rfp.id)).save()

        examples = request.POST.getlist("examples")
        primary = int(request.POST.get("primary"))
        for i, ex in enumerate(examples):
            example = Example(example=ex, primary=True if primary == i else False, definition=definition)
            example.save()
        for f, h in zip(request.FILES.getlist("upload_data"), request.POST.getlist("header")):
            link_file = "%s/%s/%s.%s" % (
                definition.author.id, definition.id, int(time.time() * 1000), f.name.split(".")[1])
            fs = FileSystemStorage()
            filename = fs.save(link_file, f)
            u = UploadData(header_for_file=h, definition=definition, image=filename)
            u.save()
        return redirect("website:definition", definition.id)
    return render(request, "website/definition/create_definition.html", {})


@login_required
def edit_definition(request, pk):
    definition = Definition.objects.get(id=pk)
    current_user = request.user.custom_user
    if definition.author != current_user:
        raise Http404()
    rfp = RequestForPublication.objects.get(definition=definition)
    if request.method == "POST":

        term = Term.objects.filter(name=request.POST["name"]).first()
        if term is None:
            term = Term(name=request.POST["name"])
            term.save()
        definition.term = term
        definition.description = request.POST["description"]
        definition.source = request.POST["source"]
        definition.date = None
        definition.save()
        if current_user.is_moderator() or current_user.is_admin():
            definition.date = datetime.now()
            definition.save()
        else:
            rfp.date_creation = datetime.now()
            rfp.status = STATUSES_FOR_REQUESTS[0][0]
            rfp.save()

        old_examples = list(definition.examples.all())
        examples = request.POST.getlist("examples")
        primary = int(request.POST.get("primary"))
        for i, ex in enumerate(examples):

templates/website/base/base_page.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Главная{% endblock %} | Современный Словарь</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"
            integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
            integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
            integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
            crossorigin="anonymous"></script>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <link href="{% static 'css/custom.css' %}" rel="stylesheet">
    {% block links %}
    {% endblock %}
    {% block style %}
    {% endblock %}
</head>
<body>
<nav id="navbarmenu" class="navbar navbar-expand-lg navbar-light fixed-top shadow" style="background: #ff7a06">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggler"
            aria-controls="navbarToggler" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="/">
        <img src="{% static 'img/logo.png' %}" height="180" width="180">
    </a>

    <div class="collapse navbar-collapse flex-column" id="navbarToggler">
        <div class="ml-auto">
            <ul class="navbar-nav flex-row">
                {% if not user.is_authenticated %}
                    <li class="nav-item horizontal first">
                        <a class="nav-link" href="/">Определения</a>
                    </li>
                    <li class="nav-item horizontal">
                        <a class="nav-link" href="{% url "website:support" %}">Поддержка</a>
                    </li>
                    <li class="nav-item horizontal">
                        <a class="nav-link" href="{% url 'login' %}">Войти</a>
                    </li>
                {% else %}
                    <li class="nav-item horizontal first">
                        <a class="nav-link" href="/">Определения</a>
                    </li>
                    <li class="nav-item horizontal">
                        <a class="nav-link" href="{% url "website:favourites_list" %}">Избранное</a>
                    </li>
                    {% if not user.custom_user.is_admin %}
                        <li class="nav-item horizontal">
                            <a class="nav-link" href="{% url "website:personal_definitions" %}">Мои определения</a>
                        </li>
                    {% endif %}
                    <li class="nav-item horizontal">
                        <a class="nav-link" href="{% url "website:support" %}">Поддержка</a>
                    </li>
                    <li class="nav-item horizontal">
                        <a class="nav-link" href="{% url "website:notifications" %}">Уведомления
                            {% if user.custom_user.get_new_notification != 0 %}
                                ({{ user.custom_user.get_new_notification }})
                            {% endif %}</a>
                    </li>
                    {% if user.custom_user.is_admin %}
                        <li class="nav-item horizontal">
                            <a class="nav-link" href="{% url "website:requests_pub" %}">Запросы на
                                публикацию</a>
                        </li>
                        <li class="nav-item horizontal">
                            <a class="nav-link" href="{% url "website:requests_for_update_status" %}">Запросы на
                                обновление статуса</a>
                        </li>
                    {% endif %}
                    <li class="nav-item horizontal">
                        <a href="{% url 'website:profile' user.id %}">
                            <img width="50px" src="{% static 'img/profile.png' %}" alt="Мой профиль">
                        </a>
                    </li>
                {% endif %}
            </ul>
        </div>
        <ul class="navbar-nav flex-row mr-auto navbar-fixed col-md-10" style="padding-top: 40px;">
            <li class="nav-item active col-md-12">
                <form action="{% url 'website:search' %}" method="get" class="form-inline">
                    <div class="input-group col-md-12">
                        <input name="q" class="form-control form-control-lg" type="search" placeholder="Поиск..."
                               aria-label="Search">
                        <div class="input-group-append">
                            <button class="btn btn-dark" type="submit"><i class="fa fa-search"></i></button>
                        </div>
                    </div>
                </form>
            </li>
            <li class="nav-item col-md-3">
                <a id="create_icon" href="{% url "website:create_definition" %}"
                   style="color: inherit; font-size: 60px"><i class="fa fa-plus-circle"></i></a>
                <a type="button" href="{% url "website:random_definition" %}" class="btn" id="random_word"
                   style="border-radius: 30px/30px; height: 50px;font-size:18px; margin-bottom: 30px; margin-left: 15px; color: #ff7a06; background: #1b1b1b;">Случайное
                    слово</a>
            </li>
        </ul>
    </div>
</nav>
<div class="main">
    <div class="container">
        {% block content %}
            <div style="margin: 30px">
                <br>
                <div class="row">
                    <div class="col-md-5">
                        <a href="#"><h3>Новое слово</h3></a>
                    </div>
                    <div class="col-md-6">
                        <h5>Автор статьи - Михаил Джекович</h5>
                        <p><i>Дата публикации- 23:41 06.11.2019г</i></p>
                    </div>
                    <div class="col-md-1">
                        <a href="#" id="favorites" data-toggle="tooltip" data-placement="bottom"
                           title="Добавить в избранное"><i class=" fa fa-heart"></i></a>
                    </div>
                </div>

                <p>Значимость этих проблем настолько очевидна, что новая модель организационной деятельности
                    представляет
                    собой интересный эксперимент проверки направлений прогрессивного развития. Таким образом реализация
                    намеченных плановых заданий способствует подготовки и реализации соответствующий условий
                    активизации.
                    Равным образом укрепление и развитие структуры обеспечивает широкому кругу (специалистов) участие в
                    формировании существенных финансовых и административных условий. Задача организации, в особенности
                    же
                    рамки и место обучения кадров играет важную роль в формировании существенных финансовых и
                    административных условий.
                </p>
                <p> Задача организации, в особенности же новая модель организационной деятельности требуют от нас
                    анализа
                    соответствующий условий активизации. Задача организации, в особенности же новая модель
                    организационной
                    деятельности в значительной степени обуславливает создание направлений прогрессивного развития.
                    Повседневная практика показывает, что дальнейшее развитие различных форм деятельности обеспечивает
                    широкому кругу (специалистов) участие в формировании направлений прогрессивного развития. Не
                    следует,
                    однако забывать, что консультация с широким активом играет важную роль в формировании
                    соответствующий
                    условий активизации. С другой стороны постоянное информационно-пропагандистское обеспечение нашей
                    деятельности в значительной степени обуславливает создание новых предложений.
                </p>
                <h3>Примеры</h3>
                <div class="jumbotron">
                    <p> Повседневная практика показывает, что дальнейшее развитие различных форм деятельности
                        обеспечивает
                        широкому кругу (специалистов) участие в формировании направлений прогрессивного развития.</p>
                    <p> Повседневная практика показывает, что дальнейшее развитие различных форм деятельности
                        обеспечивает
                        широкому кругу (специалистов) участие в формировании направлений прогрессивного развития.</p>
                </div>
                <h4>Теги</h4>
                <div>
                    <a href="#">#Семья</a>
                    <a href="#">#Быт</a>
                    <a href="#">#Дети</a>
                </div>
                <hr>
                <button class="btn btn-success"><i class="fa fa-thumbs-up">&nbsp1000</i></button>
                <button class="btn btn-danger" style="margin-left: 5px"><i class="fa fa-thumbs-down">&nbsp200</i>
                </button>
                <br>
                <br>
            </div>
        {% endblock %}
    </div>
</div>
</body>
{% block script %}
{% endblock %}
</html>

templates/website/base/page_not_found.html
{% extends 'website/base/base_page.html' %}
{% block title %}
    Страница не найдена
{% endblock %}
{% block content %}
    <div style="text-align: center;" class="row div-error"><h3>Страница не найдена <img
            src="/media/errors/404.png" style="max-width: 30%"></h3></div>
{% endblock %}

templates/website/base/server_error.html
{% extends 'website/base/base_page.html' %}
{% block title %}
    Упс!
{% endblock %}
{% block content %}
    <div style="text-align: center" class="row div-error"><h3 style="width: 100%">Упс! Что-то пошло не так!<br>К сожалению, сервер
        испытывает некоторые проблемы.<br>Наши фиксики скоро их исправят!</h3>
        <div class="img-error-center">
            <img src="/media/errors/fix.png" style="max-width: 80%">
        </div>
    </div>
{% endblock %}