api/urls.py
from django.urls import path
from api.views import *

app_name = "api"

urlpatterns = [
    path(r'definition/', definition, name='definition'),
    # path(r'', main_page, name="main_page"),
    # path(r'edit_profile/', update_profile, name='update_profile'),
    # path(r'change_password/', change_password, name="change_password"),
    # path(r'create_definition/', create_definition, name='create_definition'),
    # path(r'term/<int:pk>',  TermView.as_view(), name='term'),
    # path(r'activate_user/', activate_user, name='activate_user'),
    # path(r'random_definition', random_definition, name='random_definition'),
    # path(r'personal_definitions/', personal_definitions, name='personal_definitions'),
    # path(r'definition/<int:pk>', definition, name='definition'),
    # path(r'definition/edit/<int:pk>', edit_definition, name='edit_definition'),
    # path(r'definition/check/<int:pk>', request_for_definition, name='request_for_definition'),
    # path(r'page_not_found/', page_not_found, name='page_not_found'),
    # path(r'definition/like', like, name='like'),
    # path(r'definition/dislike', dislike, name='dislike'),
    # path(r'favourite/', favourite, name='favourite'),
    # path(r'favourites/', favourites, name='favourites_list'),
    # path(r'search/', search, name='search'),
    # path(r'requests/', requests_pub, name='requests_pub'),
    # path(r'profile/<int:pk>', UserDetailView.as_view(), name='profile')
]

urban_dictionary/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

from urban_dictionary import settings

urlpatterns = [
    path(r'admin/', admin.site.urls),
    path(r'urban/', include('website.urls', namespace="website")),
    path(r'api/', include('api.urls', namespace="api")),
    path(r'accounts/', include('django_registration.backends.activation.urls')),
    path(r'accounts/', include('django.contrib.auth.urls')),
    path(r'', RedirectView.as_view(url='/urban/', permanent=True)),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'website.views.custom_handler404'
handler500 = 'website.views.custom_handler500'

website/urls.py
from django.urls import path
from website.views import *

app_name = "website"

urlpatterns = [
    path(r'', main_page, name="main_page"),
    path(r'edit_profile/', update_profile, name='update_profile'),
    path(r'change_password/', change_password, name="change_password"),
    path(r'create_definition/', create_definition, name='create_definition'),
    path(r'term/<int:pk>', TermView.as_view(), name='term'),
    path(r'activate_user/', activate_user, name='activate_user'),
    path(r'random_definition', random_definition, name='random_definition'),
    path(r'personal_definitions/', personal_definitions, name='personal_definitions'),
    path(r'user_definitions/<int:pk>', user_definitions, name='user_definitions'),
    path(r'definition/<int:pk>', definition, name='definition'),
    path(r'definition/edit/<int:pk>', edit_definition, name='edit_definition'),
    path(r'definition/check/<int:pk>', request_for_definition, name='request_for_definition'),
    path(r'requests_update_status/', requests_for_update_status, name='requests_for_update_status'),
    path(r'definition/like', like, name='like'),
    path(r'definition/dislike', dislike, name='dislike'),
    path(r'favourite/', favourite, name='favourite'),
    path(r'favourites/', favourites, name='favourites_list'),
    path(r'search/', search, name='search'),
    path(r'requests/', requests_pub, name='requests_pub'),
    path(r'profile/<int:pk>', UserDetailView.as_view(), name='profile'),
    path(r'notifications', notifications, name='notifications'),
    path(r'update_status/<int:pk>/<str:answer>', update_status, name='update_status'),
    path(r'create_request_for_update_status', create_request_for_update_status,
         name='create_request_for_update_status'),
    path(r'support/', ask_support, name='support'),
    path(r'support/<int:pk>', answer_support, name='answer_support'),
    path(r'block/<int:pk>', block, name='block'),
    path(r'unblock/<int:pk>', unblock, name='unblock'),
    path(r'drop_file', drop_file, name='drop_file')
]

website/forms.py
from django import forms
from django.contrib.auth.models import User
from website.models import CustomUser, Support


class EditUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name')


class EditProfileForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ('description', 'photo')

website/views.py
from datetime import datetime, timedelta
import random
import time
import os.path

from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import PasswordChangeForm
from django.core.files.storage import FileSystemStorage
from django.db import transaction
from django.db.models import Q
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.shortcuts import render, redirect, get_object_or_404, render_to_response
from django.views.decorators.http import require_POST
from django_registration.forms import User
from django.core.mail import send_mail
from django.views import View
from django.template import RequestContext

from website.enums import STATUSES_FOR_REQUESTS, ACTION_TYPES, USER, DEF, RFP, RUPS, SUP, AMOUNT_NOTIF_DISPLAY
from urban_dictionary.settings import EMAIL_HOST_USER
from website.tasks import unblock_user

try:
    from django.utils import simplejson as json
except ImportError:
    import json

from website.forms import *
from website.models import Definition, CustomUser, Example, UploadData, Rating, RequestForPublication, Favorites, \
    Notification, RequestUpdateStatus, Blocking, Term, STATUSES, ROLE_CHOICES


def main_page(request):
    return render(request, 'website/main_page.html',
                  {'definitions': Definition.get_top_for_week, 'popular_for_week': True})


def custom_handler404(request, exception, template_name="page_not_found.html"):
    return render(request, 'website/base/page_not_found.html', {}, status=404)


def custom_handler500(request):
    return render(request, 'website/base/server_error.html', {}, status=500)


@login_required
@transaction.atomic
def activate_user(request):
    request.user.custom_user.status = STATUSES[0][0]
    request.user.save()
    return redirect('website:update_profile')


def ask_support(request):
    if not request.user.is_anonymous:
        if request.user.custom_user.is_admin():
            if request.method == 'POST':
                return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))
            return render(request, 'website/support_list.html',
                          {'questions': Support.objects.filter(answer__isnull=True).order_by("-date_creation")})
    if request.method == 'POST':
        question = Support(question=request.POST["question"], name=request.POST["name"], email=request.POST["email"],
                           date_creation=datetime.now())
        if not request.user.is_anonymous:
            question.user = request.user.custom_user
        question.save()
        for admin in CustomUser.objects.filter(role=3):
            Notification(date_creation=datetime.now(), user=admin,
                         action_type=ACTION_TYPES[14][0],
                         models_id="%s%s" % (SUP, question.id)).save()
        return render(request, 'website/support_done.html', {'email': question.email})
    return render(request, 'website/support.html', {})


@login_required
def answer_support(request, pk):
    if request.user.custom_user.is_admin():
        question = get_object_or_404(Support, pk=pk)
        if request.method == 'POST':
            question.answer = request.POST['answer']
            question.save()

            BASE = os.path.dirname(os.path.abspath(__file__))
            with open(os.path.join(BASE, "support_mail.txt"), 'r', encoding="utf-8") as support_mail:
                email_text = support_mail.read() \
                    .replace("question_Q8Vx q]vYfs$*7c,<tyfP|SCdr+wl+m2N{.uY.[a9&mR1zmHL}8[Xz V&36X||0t",
                             question.question) \
                    .replace("answer_q+W{ceC)}*<la~K9C{)>CLfUNY6[?c|u=JVT[)`L8*R|=qw,C?x &A:Bvv^tQD^D", question.answer)
                send_mail('Ответ на вопрос на сайте {}'.format(request.META['HTTP_HOST']),
                          email_text,
                          EMAIL_HOST_USER,
                          [question.email],
                          fail_silently=False)
            if not question.user is None:
                Notification(date_creation=datetime.now(), user=question.user,
                             action_type=ACTION_TYPES[11][0],
                             models_id="%s%s" % (SUP, question.id)).save()
            return redirect('website:support')
        return render(request, 'website/support_answer.html', {
            'question': question
        })
    else:
        redirect('website:main_page')


@login_required
@require_POST
def change_password(request):
    password_form = PasswordChangeForm(user=request.user, data=request.POST)
    if password_form.is_valid():
        password_form.save()
        update_session_auth_hash(request, password_form.user)
        return redirect('website:profile', pk=request.user.id)
    else:
        request.session['change_password_msg'] = password_form.errors
        return redirect('website:update_profile')


@login_required
@transaction.atomic
def update_profile(request):
    password_form = PasswordChangeForm(user=request.user)
    if request.method == 'POST':
        user_form = EditUserForm(request.POST, instance=request.user)
        profile_form = EditProfileForm(request.POST, instance=request.user.custom_user)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            user = profile_form.save(commit=False)
            user.photo = request.FILES.get('photo', user.photo)
            user.save()
            return redirect('website:profile', pk=user.id)
    else:
        user_form = EditUserForm(instance=request.user)
        profile_form = EditProfileForm(instance=request.user.custom_user)
        password_form._errors = request.session.pop('change_password_msg', None)
    return render(request, 'website/edit_profile.html', {
        'user_form': user_form,
        'profile_form': profile_form,
        'password_form': password_form,
        'role': ROLE_CHOICES[request.user.custom_user.role - 1][1]
    })


class UserDetailView(View):

    def get(self, request, pk):
        profile = get_object_or_404(User, pk=pk)
        if profile.custom_user.is_block():
            if request.user.is_anonymous:
                raise Http404()
            if not request.user.custom_user.is_admin():
                raise Http404()
        user_definitions = Definition.objects.filter(author_id__exact=pk)
        user_rating = str(sum(map(lambda x: x.get_likes() - x.get_dislikes(), user_definitions)))
        definition_number = Definition.objects.filter(author_id__exact=pk).count()
        return render(request, 'website/profile.html',
                      {'profile': profile,
                       'role': ROLE_CHOICES[profile.custom_user.role - 1][1],
                       'rating': user_rating,
                       'definition_number': definition_number})


@login_required
def create_definition(request):
    current_user = CustomUser.objects.get(user=request.user)
    if request.method == 'POST':
        term = Term.objects.filter(name=request.POST["name"]).first()
        if term is None:
            term = Term(name=request.POST["name"])
            term.save()
        definition = Definition(term=term, description=request.POST["description"],
                                source=request.POST["source"],
                                author=current_user)
        definition.save()
        if current_user.is_moderator() or current_user.is_admin():
            definition.date = datetime.now()
            definition.save()
        else:
            cur_date = datetime.now()
            rfp = RequestForPublication(definition=definition, date_creation=cur_date)
            rfp.save()
            for admin in CustomUser.objects.filter(role=3):
                Notification(date_creation=cur_date, user=admin, action_type=ACTION_TYPES[12][0],
                             models_id="%s%s %s%s" % (USER, current_user.id, RFP, rfp.id)).save()

        examples = request.POST.getlist("examples")
        primary = int(request.POST.get("primary"))
        for i, ex in enumerate(examples):
            example = Example(example=ex, primary=True if primary == i else False, definition=definition)
            example.save()
        for f, h in zip(request.FILES.getlist("upload_data"), request.POST.getlist("header")):
            link_file = "%s/%s/%s.%s" % (
                definition.author.id, definition.id, int(time.time() * 1000), f.name.split(".")[1])
            fs = FileSystemStorage()
            filename = fs.save(link_file, f)
            u = UploadData(header_for_file=h, definition=definition, image=filename)
            u.save()
        return redirect("website:definition", definition.id)
    return render(request, "website/definition/create_definition.html", {})


@login_required
def edit_definition(request, pk):
    definition = Definition.objects.get(id=pk)
    current_user = request.user.custom_user
    if definition.author != current_user:
        raise Http404()
    rfp = RequestForPublication.objects.get(definition=definition)
    if request.method == "POST":

        term = Term.objects.filter(name=request.POST["name"]).first()
        if term is None:
            term = Term(name=request.POST["name"])
            term.save()
        definition.term = term
        definition.description = request.POST["description"]
        definition.source = request.POST["source"]
        definition.date = None
        definition.save()
        if current_user.is_moderator() or current_user.is_admin():
            definition.date = datetime.now()
            definition.save()
        else:
            rfp.date_creation = datetime.now()
            rfp.status = STATUSES_FOR_REQUESTS[0][0]
            rfp.save()

        old_examples = list(definition.examples.all())
        examples = request.POST.getlist("examples")
        primary = int(request.POST.get("primary"))
        for i, ex in enumerate(examples):

templates/website/admin/admin_definition_check.html
{% extends 'website/base/base_page.html' %}
{% block title %}
    Проверка определения {{ rfp.definition.term.name }}
{% endblock %}
{% block content %}
    <br>
    <h3>Проверка определения {{ rfp.definition.term.name }} </h3>
    <hr>
    <div style="margin: 30px">
        <br>
        <div class="row">
            <div class="col-md-5">
                <h3>{{ rfp.definition.term.name }}</h3>
            </div>
            <div class="col-md-6">
                <h5>Автор статьи
                    - {{ rfp.definition.author.user.last_name }} {{ rfp.definition.author.user.first_name }}</h5>
                <p><i>Дата подачи запроса - {{ rfp.date_creation }}</i></p>
            </div>
        </div>
        <p>{{ rfp.definition.description }}</p>
        <h4>Примеры</h4>
        {% for example in rfp.definition.examples.all %}
            <div class="jumbotron" {% if example.primary %} style="background: #fabd94" {% endif %}>
                <p>{{ forloop.counter }}) &nbsp {{ example.example }}</p>
            </div>
        {% endfor %}
        {% for file in rfp.definition.files.all %}
            <div class="col-sm-5">
                <img class="img-fluid" id="{{ file.id }}" src="{{ file.image.url }}"
                     alt="{{ file.header_for_file }}">
            </div>
        {% endfor %}
        <br>
    </div>
    <hr>
    <h4>Выберите действие</h4>
    <hr>
    <div style="margin-left: 50px">
        <form method="post" action="{% url 'website:request_for_definition' rfp.id %}">
            {% csrf_token %}
            <div class="form-check">
                <label for="approve" class="form-check-label">
                    <input type="radio" id="approve" class="form-check-input" name="answer"
                           value="approve">Подтвердить</label>
            </div>

            <div class="form-check">
                <label for="reject" class="form-check-label">
                    <input type="radio" id="reject" class="form-check-input" name="answer" value="reject">
                    Отклонить</label>
            </div>
            <div class="form-check">
                <label for="reject_permanent" class="form-check-label">
                    <input type="radio" id="reject_permanent" class="form-check-input" name="answer"
                           value="reject_permanent">
                    Отклонить навсегда</label>
            </div>
            <div class="comment_reason" style="display: none">
                <strong>Причина отклонения</strong><textarea name="reason" class="form-control"></textarea><br>
            </div>
            <br>
            <input style="font-size: 26px" class="btn btn-success" type="submit" value="Отправить"/>
        </form>
    </div>
    <br>

{% endblock %}
{% block script %}
    <script>
        $(document).ready(function () {
            $("#approve").click(function () {
                $(".comment_reason").hide();
            });
            $("#reject_permanent").click(function () {
                $(".comment_reason").show();
            });
            $("#reject").click(function () {
                $(".comment_reason").show();
            });
        });
    </script>
{% endblock %}

templates/website/admin/requests_for_publication.html
{% extends 'website/base/base_page.html' %}
{% block title %}
    Запросы на публикацию определений
{% endblock %}
{% block content %}
    <br><br>
    <h3>Запросы на публикацию определений</h3>
    <hr>
    {% if rfps %}
        {% for rfp in rfps %}
            <a href="{% url "website:request_for_definition" rfp.id %}" style="text-decoration: none">
                <div class="jumbotron">
                    <div class="row">
                        <div class="col-md-9">
                            {{ forloop.counter }})
                            &nbsp {{ rfp.definition }}
                        </div>
                        <div class="col-md-3" style="text-align: right; font-size: 18px">
                            <p><i>{{ rfp.date_creation }}</i></p>
                        </div>
                    </div>
                </div>
            </a>
        {% endfor %}
    {% else %}
        <p>На данный момент заявок нет</p>
    {% endif %}
    <br><br>
{% endblock %}

templates/website/admin/requests_for_update_status.html
{% extends 'website/base/base_page.html' %}
{% block title %}
    Запросы на обновление статуса
{% endblock %}
{% block content %}
    <br><br>
    <h3> Запросы на обновление статуса</h3>
    <hr>
    {% if rups %}
        {% for rup in rups %}
            <div class="jumbotron">
                <div class="row">
                    <div class="col-md-9">
                        <p>Заявка на обновление статуса пользователя
                            {% if rup.user.is_block %}
                                {{ rup.user }}
                            {% else %}
                                <a
                                        href="{% url "website:profile" rup.user.id %}"> {{ rup.user }}</a> с
                                рейтингом {{ rup.user.get_rating }}</p>
                            {% endif %}
                    </div>
                    <div class="col-md-3" style="text-align: right; font-size: 18px">
                        <p><i>{{ rup.date_creation }}</i></p>
                    </div>
                </div>
                <a class="btn btn-success" href="{% url "website:update_status" rup.id "accept" %}">Принять &nbsp<i
                        class="fa fa-check"></i></a>
                <a class="btn btn-danger" href="{% url "website:update_status" rup.id "reject" %}">Отклонить &nbsp<i
                        class="fa fa-close"></i></a>
            </div>
        {% endfor %}
    {% else %}
        <p>На данный момент заявок нет</p>
    {% endif %}
    <br><br>
{% endblock %}