api/urls.py
from django.urls import path
from api.views import *

app_name = "api"

urlpatterns = [
    path(r'definition/', definition, name='definition'),
    # path(r'', main_page, name="main_page"),
    # path(r'edit_profile/', update_profile, name='update_profile'),
    # path(r'change_password/', change_password, name="change_password"),
    # path(r'create_definition/', create_definition, name='create_definition'),
    # path(r'term/<int:pk>',  TermView.as_view(), name='term'),
    # path(r'activate_user/', activate_user, name='activate_user'),
    # path(r'random_definition', random_definition, name='random_definition'),
    # path(r'personal_definitions/', personal_definitions, name='personal_definitions'),
    # path(r'definition/<int:pk>', definition, name='definition'),
    # path(r'definition/edit/<int:pk>', edit_definition, name='edit_definition'),
    # path(r'definition/check/<int:pk>', request_for_definition, name='request_for_definition'),
    # path(r'page_not_found/', page_not_found, name='page_not_found'),
    # path(r'definition/like', like, name='like'),
    # path(r'definition/dislike', dislike, name='dislike'),
    # path(r'favourite/', favourite, name='favourite'),
    # path(r'favourites/', favourites, name='favourites_list'),
    # path(r'search/', search, name='search'),
    # path(r'requests/', requests_pub, name='requests_pub'),
    # path(r'profile/<int:pk>', UserDetailView.as_view(), name='profile')
]

urban_dictionary/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

from urban_dictionary import settings

urlpatterns = [
    path(r'admin/', admin.site.urls),
    path(r'urban/', include('website.urls', namespace="website")),
    path(r'api/', include('api.urls', namespace="api")),
    path(r'accounts/', include('django_registration.backends.activation.urls')),
    path(r'accounts/', include('django.contrib.auth.urls')),
    path(r'', RedirectView.as_view(url='/urban/', permanent=True)),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'website.views.custom_handler404'
handler500 = 'website.views.custom_handler500'

website/urls.py
from django.urls import path
from website.views import *

app_name = "website"

urlpatterns = [
    path(r'', main_page, name="main_page"),
    path(r'edit_profile/', update_profile, name='update_profile'),
    path(r'change_password/', change_password, name="change_password"),
    path(r'create_definition/', create_definition, name='create_definition'),
    path(r'term/<int:pk>', TermView.as_view(), name='term'),
    path(r'activate_user/', activate_user, name='activate_user'),
    path(r'random_definition', random_definition, name='random_definition'),
    path(r'personal_definitions/', personal_definitions, name='personal_definitions'),
    path(r'user_definitions/<int:pk>', user_definitions, name='user_definitions'),
    path(r'definition/<int:pk>', definition, name='definition'),
    path(r'definition/edit/<int:pk>', edit_definition, name='edit_definition'),
    path(r'definition/check/<int:pk>', request_for_definition, name='request_for_definition'),
    path(r'requests_update_status/', requests_for_update_status, name='requests_for_update_status'),
    path(r'definition/like', like, name='like'),
    path(r'definition/dislike', dislike, name='dislike'),
    path(r'favourite/', favourite, name='favourite'),
    path(r'favourites/', favourites, name='favourites_list'),
    path(r'search/', search, name='search'),
    path(r'requests/', requests_pub, name='requests_pub'),
    path(r'profile/<int:pk>', UserDetailView.as_view(), name='profile'),
    path(r'notifications', notifications, name='notifications'),
    path(r'update_status/<int:pk>/<str:answer>', update_status, name='update_status'),
    path(r'create_request_for_update_status', create_request_for_update_status,
         name='create_request_for_update_status'),
    path(r'support/', ask_support, name='support'),
    path(r'support/<int:pk>', answer_support, name='answer_support'),
    path(r'block/<int:pk>', block, name='block'),
    path(r'unblock/<int:pk>', unblock, name='unblock'),
    path(r'drop_file', drop_file, name='drop_file')
]

website/forms.py
from django import forms
from django.contrib.auth.models import User
from website.models import CustomUser, Support


class EditUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name')


class EditProfileForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ('description', 'photo')

website/views.py
from datetime import datetime, timedelta
import random
import time
import os.path

from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import PasswordChangeForm
from django.core.files.storage import FileSystemStorage
from django.db import transaction
from django.db.models import Q
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.shortcuts import render, redirect, get_object_or_404, render_to_response
from django.views.decorators.http import require_POST
from django_registration.forms import User
from django.core.mail import send_mail
from django.views import View
from django.template import RequestContext

from website.enums import STATUSES_FOR_REQUESTS, ACTION_TYPES, USER, DEF, RFP, RUPS, SUP, AMOUNT_NOTIF_DISPLAY
from urban_dictionary.settings import EMAIL_HOST_USER
from website.tasks import unblock_user

try:
    from django.utils import simplejson as json
except ImportError:
    import json

from website.forms import *
from website.models import Definition, CustomUser, Example, UploadData, Rating, RequestForPublication, Favorites, \
    Notification, RequestUpdateStatus, Blocking, Term, STATUSES, ROLE_CHOICES


def main_page(request):
    return render(request, 'website/main_page.html',
                  {'definitions': Definition.get_top_for_week, 'popular_for_week': True})


def custom_handler404(request, exception, template_name="page_not_found.html"):
    return render(request, 'website/base/page_not_found.html', {}, status=404)


def custom_handler500(request):
    return render(request, 'website/base/server_error.html', {}, status=500)


@login_required
@transaction.atomic
def activate_user(request):
    request.user.custom_user.status = STATUSES[0][0]
    request.user.save()
    return redirect('website:update_profile')


def ask_support(request):
    if not request.user.is_anonymous:
        if request.user.custom_user.is_admin():
            if request.method == 'POST':
                return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))
            return render(request, 'website/support_list.html',
                          {'questions': Support.objects.filter(answer__isnull=True).order_by("-date_creation")})
    if request.method == 'POST':
        question = Support(question=request.POST["question"], name=request.POST["name"], email=request.POST["email"],
                           date_creation=datetime.now())
        if not request.user.is_anonymous:
            question.user = request.user.custom_user
        question.save()
        for admin in CustomUser.objects.filter(role=3):
            Notification(date_creation=datetime.now(), user=admin,
                         action_type=ACTION_TYPES[14][0],
                         models_id="%s%s" % (SUP, question.id)).save()
        return render(request, 'website/support_done.html', {'email': question.email})
    return render(request, 'website/support.html', {})


@login_required
def answer_support(request, pk):
    if request.user.custom_user.is_admin():
        question = get_object_or_404(Support, pk=pk)
        if request.method == 'POST':
            question.answer = request.POST['answer']
            question.save()

            BASE = os.path.dirname(os.path.abspath(__file__))
            with open(os.path.join(BASE, "support_mail.txt"), 'r', encoding="utf-8") as support_mail:
                email_text = support_mail.read() \
                    .replace("question_Q8Vx q]vYfs$*7c,<tyfP|SCdr+wl+m2N{.uY.[a9&mR1zmHL}8[Xz V&36X||0t",
                             question.question) \
                    .replace("answer_q+W{ceC)}*<la~K9C{)>CLfUNY6[?c|u=JVT[)`L8*R|=qw,C?x &A:Bvv^tQD^D", question.answer)
                send_mail('Ответ на вопрос на сайте {}'.format(request.META['HTTP_HOST']),
                          email_text,
                          EMAIL_HOST_USER,
                          [question.email],
                          fail_silently=False)
            if not question.user is None:
                Notification(date_creation=datetime.now(), user=question.user,
                             action_type=ACTION_TYPES[11][0],
                             models_id="%s%s" % (SUP, question.id)).save()
            return redirect('website:support')
        return render(request, 'website/support_answer.html', {
            'question': question
        })
    else:
        redirect('website:main_page')


@login_required
@require_POST
def change_password(request):
    password_form = PasswordChangeForm(user=request.user, data=request.POST)
    if password_form.is_valid():
        password_form.save()
        update_session_auth_hash(request, password_form.user)
        return redirect('website:profile', pk=request.user.id)
    else:
        request.session['change_password_msg'] = password_form.errors
        return redirect('website:update_profile')


@login_required
@transaction.atomic
def update_profile(request):
    password_form = PasswordChangeForm(user=request.user)
    if request.method == 'POST':
        user_form = EditUserForm(request.POST, instance=request.user)
        profile_form = EditProfileForm(request.POST, instance=request.user.custom_user)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            user = profile_form.save(commit=False)
            user.photo = request.FILES.get('photo', user.photo)
            user.save()
            return redirect('website:profile', pk=user.id)
    else:
        user_form = EditUserForm(instance=request.user)
        profile_form = EditProfileForm(instance=request.user.custom_user)
        password_form._errors = request.session.pop('change_password_msg', None)
    return render(request, 'website/edit_profile.html', {
        'user_form': user_form,
        'profile_form': profile_form,
        'password_form': password_form,
        'role': ROLE_CHOICES[request.user.custom_user.role - 1][1]
    })


class UserDetailView(View):

    def get(self, request, pk):
        profile = get_object_or_404(User, pk=pk)
        if profile.custom_user.is_block():
            if request.user.is_anonymous:
                raise Http404()
            if not request.user.custom_user.is_admin():
                raise Http404()
        user_definitions = Definition.objects.filter(author_id__exact=pk)
        user_rating = str(sum(map(lambda x: x.get_likes() - x.get_dislikes(), user_definitions)))
        definition_number = Definition.objects.filter(author_id__exact=pk).count()
        return render(request, 'website/profile.html',
                      {'profile': profile,
                       'role': ROLE_CHOICES[profile.custom_user.role - 1][1],
                       'rating': user_rating,
                       'definition_number': definition_number})


@login_required
def create_definition(request):
    current_user = CustomUser.objects.get(user=request.user)
    if request.method == 'POST':
        term = Term.objects.filter(name=request.POST["name"]).first()
        if term is None:
            term = Term(name=request.POST["name"])
            term.save()
        definition = Definition(term=term, description=request.POST["description"],
                                source=request.POST["source"],
                                author=current_user)
        definition.save()
        if current_user.is_moderator() or current_user.is_admin():
            definition.date = datetime.now()
            definition.save()
        else:
            cur_date = datetime.now()
            rfp = RequestForPublication(definition=definition, date_creation=cur_date)
            rfp.save()
            for admin in CustomUser.objects.filter(role=3):
                Notification(date_creation=cur_date, user=admin, action_type=ACTION_TYPES[12][0],
                             models_id="%s%s %s%s" % (USER, current_user.id, RFP, rfp.id)).save()

        examples = request.POST.getlist("examples")
        primary = int(request.POST.get("primary"))
        for i, ex in enumerate(examples):
            example = Example(example=ex, primary=True if primary == i else False, definition=definition)
            example.save()
        for f, h in zip(request.FILES.getlist("upload_data"), request.POST.getlist("header")):
            link_file = "%s/%s/%s.%s" % (
                definition.author.id, definition.id, int(time.time() * 1000), f.name.split(".")[1])
            fs = FileSystemStorage()
            filename = fs.save(link_file, f)
            u = UploadData(header_for_file=h, definition=definition, image=filename)
            u.save()
        return redirect("website:definition", definition.id)
    return render(request, "website/definition/create_definition.html", {})


@login_required
def edit_definition(request, pk):
    definition = Definition.objects.get(id=pk)
    current_user = request.user.custom_user
    if definition.author != current_user:
        raise Http404()
    rfp = RequestForPublication.objects.get(definition=definition)
    if request.method == "POST":

        term = Term.objects.filter(name=request.POST["name"]).first()
        if term is None:
            term = Term(name=request.POST["name"])
            term.save()
        definition.term = term
        definition.description = request.POST["description"]
        definition.source = request.POST["source"]
        definition.date = None
        definition.save()
        if current_user.is_moderator() or current_user.is_admin():
            definition.date = datetime.now()
            definition.save()
        else:
            rfp.date_creation = datetime.now()
            rfp.status = STATUSES_FOR_REQUESTS[0][0]
            rfp.save()

        old_examples = list(definition.examples.all())
        examples = request.POST.getlist("examples")
        primary = int(request.POST.get("primary"))
        for i, ex in enumerate(examples):

templates/website/definition/definition.html
{% extends 'website/base/base_page.html' %}
{% load custom_tags %}
{% block title %}
    Определение {{ def.term }}
{% endblock %}
{% block content %}
    <div style="margin: 30px">
        <br>
        <div class="row">
            <div class="col-md-5">
                <a href={% url 'website:term' definition.term.id %}><h3>{{ definition.term.name }}</h3></a>
                {% if user.is_authenticated and definition.author == user.custom_user %}
                    <p>Статус статьи - {% if definition.is_publish %}
                        <i style="color: green">Опубликовано</i>
                    {% else %}
                        {% if  definition.get_cur_status == 1 %}
                            <i style="color: #0a1cff">На рассмотрении </i>
                        {% elif definition.get_cur_status == 2 %}
                            <i style="color: #ff8820">Отклонен </i>
                            <br><br>
                            <a href="{% url "website:edit_definition" definition.id %}"
                               class="btn btn-light" style="background: #f9870b; color: white">Исправить</a>
                        {% elif definition.get_cur_status == 4 %}
                            <i style="color: #ff1118">Отклонен навсегда </i>
                        {% endif %}
                    {% endif %}</p>
                {% endif %}
            </div>
            <div class="col-md-6">

                <h5>Автор статьи - {% if definition.author.is_block %}
                    {{ definition.author }}
                {% else %}
                    <a href={% url 'website:profile' definition.author.id %}>{{ definition.author }}</a>
                {% endif %}
                </h5>
                {% if definition.author.user.last_name != "" or definition.author.user.last_name != "" %}
                    <h6 style="color: #4b4b4b">{{ definition.author.user.last_name }} {{ definition.author.user.first_name }}</h6>
                {% endif %}
                {% if definition.is_publish %}
                    {% if definition.date %}<p><i>Дата публикации - {{ definition.date }}</i></p>{% endif %}
                {% endif %}
            </div>
            {% if user.is_authenticated and definition.is_publish %}
                <div class="col-md-1">
                    <p class="{% is_favoured definition user %}" id="favorite{{ definition.pk }}"
                       name="{{ definition.pk }}" data-toggle="tooltip" data-placement="bottom"
                       title="Добавить в избранное"><i class=" fa fa-heart"></i></p>
                </div>
            {% endif %}
            <script>
                $('#favorite{{ definition.pk }}').click(function () {
                    $.ajax({
                        type: "POST",
                        url: "{% url 'website:favourite' %}",
                        data: {'def_id': $(this).attr('name'), 'csrfmiddlewaretoken': '{{ csrf_token }}'},
                        dataType: "json",
                        success: function (response) {
                            if (response.colour === 'black') {
                                $('#favorite{{ definition.pk }}').removeClass("favoritesadded").addClass("favorites");
                            } else {
                                $('#favorite{{ definition.pk }}').removeClass("favorites").addClass("favoritesadded");
                            }
                        },
                        fail: function (response) {
                            alert(response.responseText)
                        },
                        error: function (rs, e) {
                            debugger
                            alert(rs.responseText);
                        }
                    });
                })
            </script>
        </div>
        <h3>Описание</h3>
        <p>{{ definition.description }}</p>
        <h4>Примеры</h4>
        {% for example in definition.examples.all %}
            <div class="jumbotron" {% if example.primary %} style="background: #fabd94" {% endif %}>
                <p>{{ forloop.counter }}) &nbsp {{ example.example }}</p>
            </div>
        {% endfor %}
        {% for file in definition.files.all %}
            <div class="col-sm-5">
                <img class="img-fluid" id="{{ file.id }}" src="{{ file.image.url }}"
                     alt="{{ file.header_for_file }}">
            </div>
        {% endfor %}
        {% if definition.source %}
            <h4>Источник</h4>
            <a href="{{ definition.source }}">{{ definition.source }}</a>
        {% endif %}
        <hr>
        {% if definition.is_publish %}
            <button {% if not user.is_authenticated %} disabled {% endif %} id="like{{ definition.pk }}"
                                                       name="{{ definition.pk }}" class="btn
                                                       {% is_liked definition user %} "><i
                    class="fa fa-thumbs-up">&nbsp{{ definition.get_likes }}</i></button>
            <button {% if not user.is_authenticated %} disabled {% endif %} id="dislike{{ definition.pk }}"
                                                       name="{{ definition.pk }}" class="btn
                                                       {% is_disliked definition user %} "><i
                    class="fa fa-thumbs-down">&nbsp{{ definition.get_dislikes }}</i></button>
            <br>
            <br>
            <script>
                $('#like{{ definition.pk }}').click(function () {
                    $.ajax({
                        type: "POST",
                        url: "{% url 'website:like' %}",
                        data: {'def_id': $(this).attr('name'), 'csrfmiddlewaretoken': '{{ csrf_token }}'},
                        dataType: "json",
                        success: function (response) {
                            $('#like{{ definition.pk }}').html("<i class=\"fa fa-thumbs-up\">&nbsp" + response.likes_count + "</i>");
                            $('#dislike{{ definition.pk }}').html("<i class=\"fa fa-thumbs-down\">&nbsp" + response.dislikes_count + "</i>");
                            $("#like{{ definition.pk }}").removeClass();
                            $("#dislike{{ definition.pk }}").removeClass();
                            if (response.is_liked) {
                                $("#like{{ definition.pk }}").addClass("btn btn-success");
                                $("#dislike{{ definition.pk }}").addClass("btn btn-outline-danger");
                            } else {
                                $("#like{{ definition.pk }}").addClass("btn btn-outline-success");
                                $("#dislike{{ definition.pk }}").addClass("btn btn-outline-danger");
                            }
                        },
                        error: function (rs, e) {
                            alert(rs.responseText);
                        }
                    });
                })
            </script>
            <script>
                $('#dislike{{ definition.pk }}').click(function () {
                    $.ajax({
                        type: "POST",
                        url: "{% url 'website:dislike' %}",
                        data: {'def_id': $(this).attr('name'), 'csrfmiddlewaretoken': '{{ csrf_token }}'},
                        dataType: "json",
                        success: function (response) {
                            $('#like{{ definition.pk }}').html("<i class=\"fa fa-thumbs-up\">&nbsp" + response.likes_count + "</i>");
                            $('#dislike{{ definition.pk }}').html("<i class=\"fa fa-thumbs-down\">&nbsp" + response.dislikes_count + "</i>");
                            $("#like{{ definition.pk }}").removeClass();
                            $("#dislike{{ definition.pk }}").removeClass();
                            if (response.is_disliked) {
                                $("#like{{ definition.pk }}").addClass("btn btn-outline-success");
                                $("#dislike{{ definition.pk }}").addClass("btn btn-danger");
                            } else {
                                $("#like{{ definition.pk }}").addClass("btn btn-outline-success");
                                $("#dislike{{ definition.pk }}").addClass("btn btn-outline-danger");
                            }
                        },
                        error: function (rs, e) {
                            alert(rs.responseText);
                        }
                    });
                })
            </script>
        {% endif %}
    </div>
{% endblock %}

{% block script %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.js"></script>
{% endblock %}

templates/website/definition/edit_definition.html
{% extends 'website/base/base_page.html' %}
{% block title %}
    Редактирование определения
{% endblock %}
{% block content %}
    {% if rfp %}
        <br>
        <h3>Редактирование определения "{{ definition.term }}" </h3>
        <br>
        <h5>Причина отклонения определения</h5>
        <div class="div-error">
            <p>{{ rfp.reason }}</p>
        </div>

        <form method="post" action="{% url 'website:edit_definition' definition.id %}" enctype="multipart/form-data">
            {% csrf_token %}
            <strong>Название</strong><input type="text" name="name" class="form-control"
                                            value="{{ definition.term }}"><br>
            <strong>Описание</strong><textarea name="description"
                                               class="form-control">{{ definition.description }}</textarea><br>
            <strong>Ссылка на источник</strong><input name="source" class="form-control" type="text"
                                                      value="{{ definition.source }}"><br>
            <h5>Примеры</h5>
            {% for example in definition.examples.all %}
                <div class="row example">
                    <div class="form-group col-md-7">
                        <label>Пример {{ forloop.counter }}</label>
                        <textarea name="examples" class="form-control">{{ example.example }}</textarea>
                    </div>
                    <div class="form-group col-md-2 form-check" style="margin-top: 50px">
                        <label class="form-check-label">
                            <input type="radio" {% if example.primary %} checked {% endif %} class="form-check-input"
                                   name="primary" value="{{ forloop.counter0 }}">Основной
                        </label>
                    </div>
                    <div class="form-group col-md-3 " style="margin-top: 50px">
                        <p class="btn btn-danger del_example">Удалить пример</p>
                    </div>
                </div>
            {% endfor %}
            <br>
            <a id="add_example" class="btn btn-outline-secondary">Добавить пример</a>
            <br>
            <br>
            <h5 class="header_for_files">Прикрепить файлы к статье</h5>
            {% for file in definition.files.all %}
                <div id="file{{ file.pk }}" class="row file">
                    <div class="form-group col-md-4">
                        <label>Файл </label>
                        <img src="{{ file.image.url }}" style="max-width:70%; max-height:70%;">
                        <br>
                    </div>
                    <div class="form-group col-md-3" style="margin-top: 30px">
                        <p class="btn btn-danger" id="drop_file{{ file.pk }}" name="{{ file.pk }}">Удалить &nbsp<i
                                class="fa fa-close"></i></p>
                    </div>
                </div>
                <script>
                    $('#drop_file{{ file.pk }}').click(function () {
                        $.ajax({
                            type: "POST",
                            url: "{% url 'website:drop_file' %}",
                            data: {'file_id': $(this).attr('name'), 'csrfmiddlewaretoken': '{{ csrf_token }}'},
                            dataType: "json",
                            success: function (response) {
                                $('#file{{ file.pk }}').remove();
                            },
                            error: function (rs, e) {
                                alert(rs.responseText);
                            }
                        });
                    })
                </script>
            {% endfor %}

            <a id="add_file" class="btn btn-outline-secondary">Добавить файл</a>
            <br><br>
            <input style="font-size: 26px" class="btn btn-success" type="submit" value="Сохранить"/>
            <br><br>
        </form>
    {% endif %}
{% endblock %}
{% block script %}
    <script>
        $(document).ready(function () {
            $("#add_example").click(function () {
                var count = $(".example").length;
                $(".example:last").after("<div class=\"row example\">\n" +
                    "            <div class=\"form-group col-md-7\">\n" +
                    "                <label>Пример " + (count + 1) + " </label><textarea name=\"examples\" class=\"form-control\"></textarea>\n" +
                    "            </div>\n" +
                    "            <div class=\"form-group col-md-2 form-check\" style=\"margin-top: 50px\">\n" +
                    "                <label class=\"form-check-label\">\n" +
                    "                    <input type=\"radio\" class=\"form-check-input\" name=\"primary\" value=\"" + count + "\">Основной\n" +
                    "                </label>\n" +
                    "            </div>\n" +
                    "            <div class=\"form-group col-md-3 \" style=\"margin-top: 50px\">\n" +
                    "                <p class=\"btn btn-danger del_example\">Удалить пример</p>\n" +
                    "            </div>\n" +
                    "        </div>");
            });
            $("#add_file").click(function () {
                var count = $(".file").length + 1;
                var className = ".file:last";
                if (count === 1) {
                    className = ".header_for_files:last";
                }
                $(className).after("<div class=\"row file\">\n" +
                    "            <div class=\"form-group col-md-4\">\n" +
                    "                <label>Файл</label><input class=\"form-control-file\" type=\"file\" name=\"upload_data\">\n" +
                    "            </div>\n" +
                    "            <div class=\"form-group col-md-5\">\n" +
                    "                <label> Подпись к фотографии\n" +
                    "                    <input name=\"header\" class=\"form-control\" type=\"text\">\n" +
                    "                </label>\n" +
                    "            </div>\n" +
                    "            <div class=\"form-group col-md-3\" style=\"margin-top: 30px\">\n" +
                    "                <p class=\"btn btn-danger del_file\">Удалить файл</p>\n" +
                    "            </div>\n" +
                    "        </div>");

            });
            $('.container').on('click', '.del_example', function () {
                if ($(".example").length !== 1) {
                    $(this).parent().parent().remove();
                    $(".example").each(function (i) {
                        $(this).find(".form-check").children().children().val(i);
                        $(this).find(".col-md-7").children().first().text("Пример " + (i + 1));
                    });
                }
            });

            $('.container').on('click', '.del_file', function () {
                if ($(".file").length !== 1) {
                    $(this).parent().parent().remove();
                    $(".file").each(function (i) {
                        $(this).find(".col-md-4").children().first().text("Файл " + (i + 1));
                    });
                }
            });
        });

    </script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.js"></script>
{% endblock %}